/// Set all standardized texts
import 'package:get/get.dart';

class Messages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'title': 'Expressive',
          "untitled": "Untitled",
          "viewNote": "View",
          "AINote": "AI-assist"
        },
      };
}

const supportedInkRecognitionLanguage = {
  "af": "Afrikaans",
  "am": "Amharic",
  "ar": "Arabic",
  "as": "Assamese",
  "be": "Belarusian",
  "bg": "Bulgarian",
  "bn": "Bengali",
  "bs": "Bosnian",
  "ca": "Catalan",
  "cs": "Czech",
  "cy": "Welsh",
  "da": "Danish",
  "de": "German",
  "el": "Greek",
  "en": "English",
  "eo": "Esperanto",
  "es": "Spanish",
  "et": "Estonian",
  "eu": "Basque",
  "fa": "Persian",
  "fi": "Finnish",
  "fr": "French",
  "fy": "Western Frisian",
  "ga": "Irish",
  "gl": "Galician",
  "gu": "Gujarati",
  "gv": "Manx",
  "he": "Hebrew",
  "hi": "Hindi",
  "hr": "Croatian",
  "hu": "Hungarian",
  "hy": "Armenian",
  "id": "Indonesian",
  "is": "Icelandic",
  "it": "Italian",
  "ja": "Japanese",
  "ka": "Georgian",
  "kk": "Kazakh",
  "kl": "Kalaallisut",
  "km": "Khmer",
  "kn": "Kannada",
  "ko": "Korean",
  "lb": "Luxembourgish",
  "lo": "Lao",
  "lt": "Lithuanian",
  "lv": "Latvian",
  "mg": "Malagasy",
  "mk": "Macedonian",
  "ml": "Malayalam",
  "mr": "Marathi",
  "ms": "Malay",
  "mt": "Maltese",
  "my": "Burmese",
  "ne": "Nepali",
  "no": "Norwegian",
  "om": "Oromo",
  "or": "Oriya",
  "pa": "Punjabi",
  "pl": "Polish",
  "pt": "Portuguese",
  "ru": "Russian",
  "si": "Sinhala",
  "sk": "Slovak",
  "sl": "Slovenian",
  "so": "Somali",
  "sq": "Albanian",
  "sw": "Swahili",
  "ta": "Tamil",
  "te": "Telugu",
  "th": "Thai",
  "ti": "Tigrinya",
  "uk": "Ukrainian",
  "ur": "Urdu",
  "vi": "Vietnamese",
  "zu": "Zulu"
};
